import local from 'next/font/local';
import Header from '@/components/header/header';
import { locales } from '@/app/i18n/settings';
import '../globals.scss';

const cygre = local({
  src: [
    {
      path: '../../../public/fonts2/Cygre-Medium.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
});

export const metadata = {
  title: 'Falsch-parker',
  description: 'Generated by create next app',
};

export const generateStaticParams = () => {
  return locales.map((locale) => ({ lang: locale }));
};

const RootLayout = ({ children, params: { lang } }) => {
  return (
    <html lang={lang}>
      <body className={cygre.className}>
        <Header lang={lang} />
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
