import local from 'next/font/local';
import './globals.css';
import Header from '@/components/header/header';

const cygre = local({
  src: [
    {
      path: '../../public/fonts/Cygre-Regular.ttf',
      weight: '600',
      style: 'normal',
    },
  ],
});

export const metadata = {
  title: 'Falsch-parker',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={cygre.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
